name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
      - name: Generate Playwright HTML report
        run: npx playwright show-report --output=playwright-report
      - name: Zip Playwright HTML report
        run: zip -r playwright-report.zip playwright-report
      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Playwright Test Report - ${{ job.status == 'success' && 'PASSED' || 'FAILED' }}
          to: sathyanarayanan.prabhu@ideas2it.com
          from: Playwright CI <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hi Sathyanarayanan,

            The Playwright CI/CD run has completed with status: ${{ job.status == 'success' && 'PASSED' || 'FAILED' }}.

            Please find the attached Playwright test report (unzip and open index.html).

            Regards,
            CI/CD
          attachments: playwright-report.zip 